Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vm.hostname = "ibex"
  config.vm.network "forwarded_port", guest: 22, host: 2211
  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.name = "ibex"
    virtualbox.customize [
                           "modifyvm", :id,
                           "--nicpromisc2", "allow-vms",
                           "--natdnshostresolver1", "on"
                         ]
    end
  config.vm.synced_folder "..", "/var/ibex"
  config.vm.provision :shell, path: "./packages.sh"
  config.vm.provision :shell, path: "./dev_env.sh"
  config.vm.provision :shell, path: "./postgres.sh"
  config.vm.provision :shell, path: "./schema.sh"
end 